services:
  - type: cron
    name: attendance-marker
    runtime: docker
    plan: free
    schedule: "30 2,13 * * 1-5"  # Runs at 8 am and 7pm IST monday to friday, adjust as needed
    region: singapore  # Choose appropriate region
    envVars:
      - key: HR_USER
        sync: false
      - key: HR_PASSWORD
        sync: false
      - key: GOOGLE_EMAIL
        sync: false
      - key: GOOGLE_PASSWORD
        sync: false